### ISSUE TITLE
Boot loop on Xperia 5 IV (XQ-CQ54) android-13.0.0_r51

### ISSUE THREAD

**Issue by kamsad** [sonyxperiadev/local_manifests#144]
I followed steps from [here](https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/)and flashed all the images listed. Device goes into boot loop.

Erased it with Emma tool that installs Android 12. Went back to flashing again and this time locked the bootloader as well. I get "this software is untrusted....5 second shutdown" message.

(Same boot loop occurred when I tried with android-13.0.0_r34 - however, that built had many errors and platform wasn't Ubuntu 18 either)

Can someone please guide or point me in the right direction for this device to run Android 13? So far, my main challenge is 'boot loop' after the images are flashed. 

Should I try 'fastboot flashall -w" ? Instead of flashing each image? Do I have to erase any cache partitions?

Device was shipped with Android 13 - but Emma is only flashing it back to Android 12.

**Comment by jerpelea** [comment]
Hi @kamsad,

we released the latest Android 13 OFW on Flashtool so that you can recover the device

this is my flash script 

fastboot reboot fastboot
fastboot wipe-super
fastboot flash boot_a boot.img
fastboot flash dtbo_a dtbo.img
fastboot flash recovery_a recovery.img
fastboot flash --disable-verity --disable-verification vbmeta vbmeta.img
fastboot flash --disable-verity --disable-verification vbmeta_system vbmeta_system.img
fastboot flash oem_a odm.img
fastboot flash vendor_boot_a vendor_boot.img
fastboot flash product_a product.img
fastboot flash system_a system.img
fastboot flash vendor_a vendor.img
fastboot flash vendor_dlkm_a vendor_dlkm.img
fastboot flash system_ext_a system_ext.img
fastboot flash userdata userdata.img
fastboot erase metadata
fastboot --set-active=a

please provide dmesg/logcat so that we can investigate the issue

Thanks 
Alin

**Comment by jerpelea** [comment]
please continue the thread on the bugtracker 
https://github.com/sonyxperiadev/bug_tracker/
